drop table skok cascade;
drop table kraj cascade;
drop table konkurs cascade;
drop table Zawodnik cascade;
drop table KwotaStartowa cascade;
drop table Zgloszenie cascade;
drop type statusK;
drop type rodzajSerii;
drop FUNCTION sprawdzZgloszenie();
drop FUNCTION czyKwalifikacyjna(id_k INTEGER);